### ISSUE TITLE
create Loanshark Model

### ISSUE THREAD

**Issue by melvintzw** [CS2103JAN2018-F12-B4/main#57]
#58 
Create Customer
- [x] create Customer class
- [x] modify tokenizer and addCommandParser to accept new arguments (moneyOwed & interestRate) and to construct the correct AddCommand object

Create Runner
- [x] create Runner class
- [x] modify tokenizer and addCommandParser to accept new arguments (list of Persons) and to construct the correct AddCommand object

#75 Modify AddCommand
Modify EditCommand
Modify FindCommand

**Comment by melvintzw** [comment]
all main functionality is done
