### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by jonleeyz** [CS2103JAN2018-F12-B4/main#63]
- [x] `Alt` + `Q` | **Exits** the application.
- [x] `Alt` + `A` | **Adds a new person**: adds `AddCommand` prefixes and displays relevant help information.
- [x] `Alt` + `E` | **Edits a person**: adds `EditCommand` prefix and displays relevant help information.
- [x] `Alt` + `D` | **Deletes a person**: adds `DeleteCommand` prefix and displays relevant help information.
- [x] `Alt` + `L` | **Locates a person**: adds `LocateCommand` prefix and displays relevant help information.
- [x] `Alt` + `F` | **Finds a person**: adds `FindCommand` prefix and displays relevant help information.

More keyboard configurations possible.

What do you guys think? I think this is a very good usability enhancement we can do.

**Comment by melvintzw** [comment]
I think these are great but it might be better to focus on LoanShark specific enhancements for now! Since we haven't got a baseline useful app that would be useful for a loanshark manager.

**Comment by jonleeyz** [comment]
Implemented in PR #79. Issue closed.
